export * as cleverbot from './cleverbot/index.js'
export * as fun       from './fun/index.js'
export * as info      from './info/index.js'
export * as users     from './users/index.js'
export * as weather   from './weather/index.js'
export * as spotify   from './spotify/index.js'