GuildSettings:
  type: object
  properties:
    nickname:
      type: string
      description: The nickname of bot in the guild
    color:
      type: string
      description: The color of the embeds
      example: "#FF0000"
    timezone:
      type: string
      description: The timezone of the guild
      example: "UTC"
  required:
    - color
    - timezone